### PR TITLE
add my folder

### PR DESCRIPTION
**Pull request by romanfedyshyn**

### CODE REVIEW

**Comment by CubaSAN** [comment]
Please add just index.html file to repo to have possibility to finish pull request

**Comment by romanfedyshyn** [comment]
i already add index.html

**Comment by CubaSAN** [comment]
remove this readmy md strange file

**Comment by CubaSAN** [comment]
hi file

**Comment by romanfedyshyn** [comment]
complete. i guess

**Comment by CubaSAN** [comment]
no I see changes in readme md, should be only files added not change anything

**Comment by romanfedyshyn** [comment]
i don't change anything, just add my folder where is my index.html file is. and on my branch stay your .gitignore file

**Pull request closed without merging**
